{
 "title": "K8S Kubeletstats",
 "description": "Monitors kubernetes pods using kubeletstat metrics scraped using Otel's kubeletstats receiver and Otel's Kubernetes cluster receiver",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod_name", "label": "Pod Name", "query": { "query": "label_values(k8s_pod_name)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU Usage",
   "type": "gauge",
   "description": "This metric measures the average CPU utilization across all the containers in a given Pod. It represents the overall CPU utilization of the Pod, including all the containers running within it.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_cpu_utilization_ratio{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Pod {{k8s_pod_name}} CPU Usage"
    }
   ]
  },
  {
   "title": "Pod Used RAM",
   "type": "piechart",
   "description": "This metric measures the memory utilization across all the containers in a given Pod. It represents the overall memory utilization of the Pod, including all the containers running within it.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_memory_available_bytes{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Available RAM {{k8s_pod_name}}"
    },
    {
     "expr": "k8s_pod_memory_usage_bytes{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Used RAM {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_container_restarts_ratio{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources - CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k8s_container_cpu_limit{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Limit for {{k8s_container_name}} from {{k8s_pod_name}}"
    },
    {
     "expr": "k8s_container_cpu_request{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Request for {{k8s_container_name}} from {{k8s_pod_name}}"
    },
    {
     "expr": "rate(container_cpu_time_seconds_total{k8s_pod_name=\"$pod_name\"}[1m])",
     "legendFormat": "Usage for {{k8s_container_name}} from {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Container {{k8s_container_name}} used CPU"
    }
   ]
  },
  { "title": "Resources - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Container {{k8s_container_name}} Used RAM"
    },
    {
     "expr": "k8s_container_memory_limit{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Limit for {{k8s_container_name}} from {{k8s_pod_name}}"
    },
    {
     "expr": "k8s_container_memory_request{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Request for {{k8s_container_name}} from {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k8s_pod_memory_usage_bytes{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Pod {{k8s_pod_name}} Used RAM"
    },
    {
     "expr": "k8s_pod_memory_available_bytes{k8s_pod_name=\"$pod_name\"}",
     "legendFormat": "Pod {{k8s_pod_name}} Available RAM"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem stats (containers)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_filesystem_capacity_bytes{k8s_pod_name=\"$pod_name\"}",
       "legendFormat": "Filesystem Capacity for {{k8s_container_name}}"
      },
      {
       "expr": "container_filesystem_available_bytes{k8s_pod_name=\"$pod_name\"}",
       "legendFormat": "Available storage for {{k8s_container_name}}"
      },
      {
       "expr": "container_filesystem_usage_bytes{k8s_pod_name=\"$pod_name\"}",
       "legendFormat": "Used storage for {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Network IO ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(k8s_pod_network_io_bytes_total{k8s_pod_name=\"$pod_name\", direction=\"receive\"}[1m])",
       "legendFormat": "Received {{k8s_pod_name}}"
      },
      {
       "expr": "- rate(k8s_pod_network_io_bytes_total{k8s_pod_name=\"$pod_name\", direction=\"transmit\"}[1m])",
       "legendFormat": "Sent {{k8s_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}